name: Publish DDOLib-Scala

on:
  push:
    tags:
      - 'v*'   # trigger on tag vX.X.X

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Setup Java
        uses: actions/setup-java@v5.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Install sbt
        uses: sbt/setup-sbt@v1
        
      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo RELOADAGENT | gpg-connect-agent
          gpg --list-keys

      - name: Setup Maven settings.xml
        run: |
          mkdir -p $HOME/.m2
          cat > $HOME/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                    https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>central</id>
                <username>${{ secrets.MVN_USERNAME }}</username>
                <password>${{ secrets.MVN_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build and deploy
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          sbt clean compile
          sbt +publishSigned
          sbt sonatypeBundleRelease