name: Publish DDOLib-Scala

on:
  push:
    tags:
      - 'v*'   # trigger on tag vX.X.X

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Setup Java
        uses: actions/setup-java@v5.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Install sbt
        uses: sbt/setup-sbt@v1

      - name: Build and deploy
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.MVN_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.MVN_PASSWORD }}
        run: |
          # Configure GPG for non-interactive mode
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent || true
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

          sbt "clean; compile; publishSigned; sonaRelease"
